only_build_toc_files: true

repository:
  url                       : https://github.com/sterrettJD/CSCI-6118-Project  # Online location of your book
#  path_to_book              : /Notebooks/  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"